name: Maven Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 16]

    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    - run: java -version && mvn --version
    - run: mvn --activate-profiles dist --no-transfer-progress package
    - uses: actions/upload-artifact@v2-preview
      with:
        name: BungeeCord
        path: bootstrap/target/BungeeCord.jar
